spring:
  datasource:
    url: jdbc:postgresql://localhost:5687/health-tracker
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        show_sql: true
logging:
  level:
    net:
      ttddyy:
        dsproxy:
          listener: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"