spring:
    datasource:
        url: jdbc:postgresql://localhost:5687/health-tracker
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: password
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
    flyway:
        baseline-on-migrate: true