spring:
    jpa:
        properties:
            hibernate:
                show_sql: true
logging:
    level:
        org:
            springframework:
                web: debug

POSTGRES_HOST: localhost
POSTGRES_PORT: 5687
POSTGRES_DB: health-tracker
POSTGRES_USER: postgres
POSTGRES_PASSWORD: password